apiVersion: v1
kind: Service
metadata:
  name: udagram-user-api-app
  labels:
    run: udagram-user-api-app
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    run: udagram-user-api-app